// Translation dictionary - COMPLETE
const translations = {
  en: {
    "meta.title": "Miran Livestock | International Livestock Trading & Export",
    "meta.description": "EU certified livestock trading and export services. Cattle, sheep & goats for international markets.",
    "nav.home": "Home",
    "nav.services": "Services",
    "nav.offers": "Offers",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.language": "Language:",
    "hero.badge": "EU Certified Operations",
    "hero.title": "International Livestock<br>Trading & Export",
    "hero.subtitle": "Premium cattle, sheep & goats sourced from trusted networks across Europe.<br>Full regulatory compliance with veterinary certification and logistics.",
    "hero.cred1": "EU Certified Trading",
    "hero.cred2": "Approved Quarantine",
    "hero.cred3": "Global Logistics",
    "hero.cta1": "Request a Quote",
    "hero.cta2": "Explore Services",
    "hero.scroll": "Scroll to explore",
    "services.label": "What We Do",
    "services.title": "Our Core Services",
    "services.desc": "Comprehensive livestock solutions from sourcing to delivery",
    "services.export.title": "Animal Export Services",
    "services.export.desc": "International livestock export operations with full veterinary and regulatory compliance.",
    "services.trading.title": "Livestock Trading",
    "services.trading.desc": "Professional sourcing and trading of cattle, sheep, and goats across EU markets.",
    "services.quarantine.title": "Quarantine Facilities",
    "services.quarantine.desc": "Approved quarantine and holding facilities prepared for international export.",
    "services.link": "Learn more",
    "process.label": "The Journey",
    "process.title": "How Our Export Process Works",
    "process.desc": "From selection to delivery, we ensure quality at every step",
    "process.step1.title": "Sourcing",
    "process.step1.desc": "We identify livestock that meets your specifications and quality requirements through our trusted supplier network.",
    "process.step2.title": "Veterinary Checks",
    "process.step2.desc": "Animals undergo full health inspection and certification according to EU and destination country standards.",
    "process.step3.title": "Quarantine",
    "process.step3.desc": "Approved facilities ensure compliance, monitoring and readiness for export.",
    "process.step4.title": "Export & Logistics",
    "process.step4.desc": "Transport coordination, documentation and delivery to final destination.",
    "updates.label": "Latest News",
    "updates.title": "Company Updates",
    "updates.desc": "Recent operations, exports, and market activity",
    "updates.item1.date": "February 2026",
    "updates.item1.title": "Cattle Export to Middle East",
    "updates.item1.desc": "Successfully delivered 500 head of premium cattle to our partners in the UAE.",
    "updates.item2.date": "January 2026",
    "updates.item2.title": "Facility Expansion",
    "updates.item2.desc": "Expanded quarantine facilities to accommodate growing export demands.",
    "updates.item3.date": "December 2025",
    "updates.item3.title": "New Transport Partnership",
    "updates.item3.desc": "Partnered with leading logistics providers for seamless EU-wide transport.",
    "contact.label": "Get in Touch",
    "contact.title": "Ready to Export?<br>Let's Talk.",
    "contact.desc": "Whether you need cattle, sheep, or goats, our team is ready to handle your international livestock requirements with precision and care.",
    "contact.email": "Email",
    "contact.phone": "Phone",
    "contact.location": "Location",
    "contact.form.title": "Request a Quote",
    "contact.form.firstName": "First Name",
    "contact.form.lastName": "Last Name",
    "contact.form.emailLabel": "Email Address",
    "contact.form.animal.placeholder": "Select Animal Type",
    "contact.form.animal.cattle": "Cattle",
    "contact.form.animal.sheep": "Sheep",
    "contact.form.animal.goats": "Goats",
    "contact.form.animal.mixed": "Mixed",
    "contact.form.animal.label": "Animal Type",
    "contact.form.message": "Your Requirements",
    "contact.form.submit": "Send Request",
    "footer.desc": "EU certified livestock trading and export services. Connecting quality livestock with international markets since 2010.",
    "footer.links": "Quick Links",
    "footer.services": "Services",
    "footer.logistics": "Logistics",
    "footer.contact": "Contact",
    "footer.rights": "All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    //ABOUT
    "about.meta.title": "About Us | Miran Livestock",
    "about.meta.description": "Learn about Miran Livestock - EU certified livestock trading and export company based in Bulgaria.",
    "about.breadcrumb.home": "Home",
    "about.hero.title": "About Miran Livestock",
    "about.hero.subtitle": "Connecting quality livestock with international markets through trusted partnerships and certified operations.",
    "about.story.label": "Our Story",
    "about.story.title": "Trusted Livestock Partners Since 2010",
    "about.story.lead": "Miran Livestock is a EU-certified livestock trading and export company headquartered in Razgrad, Bulgaria. We specialize in connecting quality cattle, sheep, and goats with international markets.",
    "about.story.p1": "Our operations span the entire livestock export chain—from sourcing through our extensive network of trusted European suppliers, to veterinary certification, quarantine management, and final delivery to destinations across the Middle East, North Africa, and beyond.",
    "about.story.p2": "With over 15 years of experience, we have built a reputation for reliability, transparency, and excellence in animal welfare. Our team of veterinarians, logistics specialists, and trading experts work together to ensure every export meets the highest standards.",
    "about.story.badge": "Years of<br>Excellence",
    "about.stats.animals": "Animals Exported",
    "about.stats.countries": "Countries Served",
    "about.stats.satisfaction": "Client Satisfaction",
    "about.mission.label": "Our Mission",
    "about.mission.title": "Excellence in Every Export",
    "about.mission.p1": "We believe that quality livestock export requires more than just logistics—it demands dedication to animal welfare, strict compliance with international regulations, and genuine partnerships with our clients.",
    "about.mission.p2": "Our mission is to bridge the gap between European livestock producers and international markets, ensuring that every animal we export arrives healthy, documented, and ready for its new environment.",
    "about.mission.point1": "Uncompromising animal welfare standards",
    "about.mission.point2": "Full regulatory compliance and transparency",
    "about.mission.point3": "Long-term partnerships with clients and suppliers",
    "about.values.label": "Our Principles",
    "about.values.title": "Why Choose Us",
    "about.values.desc": "The values that drive everything we do",
    "about.values.quality.title": "Certified Quality",
    "about.values.quality.desc": "Every animal meets strict EU health and welfare standards before export. Complete documentation and traceability guaranteed.",
    "about.values.network.title": "Trusted Network",
    "about.values.network.desc": "Long-standing relationships with verified suppliers across Europe and established partnerships with buyers worldwide.",
    "about.values.efficiency.title": "Efficient Logistics",
    "about.values.efficiency.desc": "Streamlined transport coordination ensuring timely, safe delivery. We handle all documentation and customs requirements.",
    "about.values.global.title": "Global Reach",
    "about.values.global.desc": "Exporting to markets across the Middle East, North Africa, and beyond. We understand diverse market requirements.",
    "about.team.label": "Leadership",
    "about.team.title": "Meet Our Team",
    "about.team.desc": "Experienced professionals dedicated to your success",
    "about.team.founder": "Founder & CEO",
    "about.team.founder.desc": "15+ years in livestock export, established Miran Livestock in 2010.",
    "about.team.vet": "Head Veterinarian",
    "about.team.vet.desc": "EU-certified veterinary specialist ensuring health compliance.",
    "about.team.operations": "Operations Manager",
    "about.team.operations.desc": "Expert in logistics and international trade regulations.",
    "about.team.sales": "Sales Director",
    "about.team.sales.desc": "Building lasting relationships with clients across 25+ countries.",
    "about.partners.label": "Trusted By",
    "about.partners.title": "Our Partners",
    "about.partners.desc": "Collaborating with industry leaders to deliver excellence",
    "about.cta.title": "Let's Work Together",
    "about.cta.desc": "Partner with a trusted name in international livestock export.",
    "about.cta.button1": "Get in Touch",
    "about.cta.button2": "View Services",
    //CONTACT
    "contact.meta.title": "Contact Us | Miran Livestock",
"contact.meta.description": "Get in touch with Miran Livestock for international livestock export inquiries. Office in Razgrad, Bulgaria.",
"contact.breadcrumb.home": "Home",
"contact.hero.title": "Get in Touch",
"contact.hero.subtitle": "Ready to export? We're here to help. Reach out for quotes, questions, or partnership inquiries.",
"contact.card.address.title": "Visit Us",
"contact.card.address.sub": "Main office & quarantine facilities",
"contact.card.phone.title": "Call Us",
"contact.card.phone.sub": "Mon-Fri: 8:00 - 18:00 EET",
"contact.card.call": "Call now",
"contact.card.email.title": "Email Us",
"contact.card.email.sub": "We reply within 24 hours",
"contact.card.send": "Send email",
"contact.card.whatsapp.title": "WhatsApp",
"contact.card.whatsapp.sub": "Quick replies for urgent inquiries",
"contact.card.chat": "Start chat",
"contact.form.heading": "Send Us a Message",
"contact.form.intro": "Fill out the form below and we'll get back to you within 24 hours.",
"contact.form.firstName": "First Name *",
"contact.form.lastName": "Last Name *",
"contact.form.email": "Email Address *",
"contact.form.phone": "Phone Number",
"contact.form.company": "Company Name",
"contact.form.animal.cattle": "Cattle",
"contact.form.animal.sheep": "Sheep",
"contact.form.animal.goats": "Goats",
"contact.form.animal.mixed": "Mixed",
"contact.form.animal.label": "Animal Type *",
"contact.form.quantity": "Estimated Quantity (head)",
"contact.form.destination.other": "Other",
"contact.form.destination.label": "Destination Country *",
"contact.form.message": "Your Message *",
"contact.form.submit": "Send Message",
"contact.office.title": "Main Office",
"contact.office.hours": "Business Hours",
"contact.office.mon": "Monday - Friday:",
"contact.office.sat": "Saturday:",
"contact.office.sun": "Sunday:",
"contact.office.closed": "Closed",
"contact.faq.label": "FAQ",
"contact.faq.title": "Frequently Asked Questions",
"contact.faq.desc": "Quick answers to common questions",
"contact.faq.q1": "How long does the export process take?",
"contact.faq.a1": "The typical export process takes 2-4 weeks from order confirmation to delivery. This includes sourcing, veterinary checks, quarantine (7-14 days depending on destination), and transport arrangements.",
"contact.faq.q2": "What documents do you provide?",
"contact.faq.a2": "We provide all necessary export documentation including: Veterinary Health Certificate, EU Export Certificate, Origin Certificate, CITES permits (if required), and customs documentation for the destination country.",
"contact.faq.q3": "Which countries do you export to?",
"contact.faq.a3": "We regularly export to UAE, Qatar, Saudi Arabia, Kuwait, Jordan, Libya, and other Middle Eastern and North African countries. We can also arrange exports to other destinations based on your requirements.",
"contact.faq.q4": "What is the minimum order quantity?",
"contact.faq.a4": "We accommodate orders of various sizes. While we specialize in commercial volumes (50+ head), we can discuss smaller orders depending on the destination and current availability. Contact us for specific requirements.",
"contact.faq.q5": "How do you ensure animal welfare during transport?",
"contact.faq.a5": "Animal welfare is our top priority. We use EU-approved transport vehicles with proper ventilation, spacing, and rest stops. All journeys comply with EU animal transport regulations, and we provide veterinary supervision for longer routes.",
"contact.faq.q6": "What payment terms do you offer?",
"contact.faq.a6": "We typically require a 30% deposit upon order confirmation, with the remaining 70% due before shipment. For established partners, we can discuss alternative payment arrangements including letters of credit.",
"contact.cta.title": "Ready to Start Your Export?",
"contact.cta.desc": "Our team is standing by to discuss your livestock requirements.",
"contact.cta.call": "Call Us Now",
"contact.cta.offers": "View Current Offers",
//SERVICES
"services.meta.title": "Services | Miran Livestock",
"services.meta.description": "Comprehensive livestock services including export, trading, and quarantine facilities.",
"services.hero.title": "Our Services",
"services.hero.subtitle": "International livestock sourcing, trading and export. Fully compliant veterinary, quarantine and logistics operations.",
"services.breadcrumb.home": "Home",
"services.export.tag": "Primary Service",
"services.export.title": "Animal Export Services",
"services.export.lead": "Full-service international export of cattle, sheep and goats, including documentation, veterinary certification and transport coordination.",
"services.export.feature1.title": "EU Compliant Procedures",
"services.export.feature1.desc": "All exports meet strict EU regulations and standards",
"services.export.feature2.title": "Veterinary Inspections",
"services.export.feature2.desc": "Complete health checks and certifications",
"services.export.feature3.title": "Customs & Documentation",
"services.export.feature3.desc": "Full paperwork handling for smooth clearance",
"services.export.feature4.title": "Transport Coordination",
"services.export.feature4.desc": "End-to-end logistics management",
"services.export.cta": "Inquire About Export",
"services.trading.tag": "Core Service",
"services.trading.title": "Livestock Trading",
"services.trading.lead": "Reliable sourcing and trading of quality livestock across Europe and international markets, tailored to your specific requirements.",
"services.trading.feature1.title": "Trusted Supplier Network",
"services.trading.feature1.desc": "Access to verified farms across the EU",
"services.trading.feature2.title": "Breed & Weight Selection",
"services.trading.feature2.desc": "Precise matching to your specifications",
"services.trading.feature3.title": "Flexible Volumes",
"services.trading.feature3.desc": "From small orders to large commercial batches",
"services.trading.feature4.title": "Market Insights",
"services.trading.feature4.desc": "Expert guidance on timing and pricing",
"services.trading.cta": "Discuss Trading Options",
"services.quarantine.tag": "Facility Service",
"services.quarantine.title": "Quarantine Facilities",
"services.quarantine.lead": "Approved quarantine and holding facilities ensuring compliance with destination country regulations and optimal animal welfare.",
"services.quarantine.feature1.title": "Health Monitoring",
"services.quarantine.feature1.desc": "Continuous veterinary supervision",
"services.quarantine.feature2.title": "Isolation Protocols",
"services.quarantine.feature2.desc": "Strict biosecurity measures",
"services.quarantine.feature3.title": "Biosecurity Standards",
"services.quarantine.feature3.desc": "Elevated hygiene and safety protocols",
"services.quarantine.feature4.title": "Pre-export Preparation",
"services.quarantine.feature4.desc": "Readiness checks and documentation",
"services.quarantine.cta": "Book Facility Space",
"services.process.label": "The Process",
"services.process.title": "How It Works",
"services.process.desc": "Four steps from inquiry to delivery",
"services.process.step1": "Sourcing",
"services.process.step1.desc": "We identify livestock matching your specifications through our trusted network.",
"services.process.step2": "Veterinary Checks",
"services.process.step2.desc": "Full health inspection and certification per EU and destination standards.",
"services.process.step3": "Quarantine",
"services.process.step3.desc": "Compliance monitoring and readiness preparation in approved facilities.",
"services.process.step4": "Export & Logistics",
"services.process.step4.desc": "Coordinated transport, documentation, and delivery to destination.",
"services.cta.title": "Ready to Start Your Export?",
"services.cta.desc": "Our team is standing by to discuss your livestock requirements and provide a customized quote.",
"services.cta.quote": "Request a Quote",
"services.cta.call": "Call Us Now",
"offers.meta.title": "Livestock Offers | Miran Livestock",
"offers.meta.description": "Browse our available cattle, sheep, and goats for export. All livestock is EU certified and export-ready.",
"offers.hero.title": "Current Livestock Offers",
"offers.hero.subtitle": "Browse our available animals ready for export. All livestock is EU certified and export-ready.",
"offers.breadcrumb.home": "Home",
"offers.filter.all": "All Animals",
"offers.filter.cattle": "Cattle",
"offers.filter.sheep": "Sheep",
"offers.filter.goats": "Goats",
"offers.card.available": "Available Now",
"offers.card.coming": "Coming Soon",
"offers.card.head": "head",
"offers.card.age": "Age",
"offers.card.weight": "Weight",
"offers.card.health": "Health",
"offers.card.inquire": "Inquire Now",
"offers.card.preorder": "Pre-order",
"offers.cta.title": "Don't See What You Need?",
"offers.cta.desc": "We source specific breeds and quantities on request. Tell us your requirements.",
"offers.cta.button": "Custom Request"
  },
  
  bg: {
    "meta.title": "Miran Livestock | Международна Търговия с Животни",
    "meta.description": "Сертифицирани от ЕС услуги за търговия и износ на животни. Говеда, овце и кози за международните пазари.",
    "nav.home": "Начало",
    "nav.services": "Услуги",
    "nav.offers": "Оферти",
    "nav.about": "За Нас",
    "nav.contact": "Контакти",
    "nav.language": "Език:",
    "hero.badge": "Сертифицирани от ЕС",
    "hero.title": "Международна Търговия<br>с Животни и Износ",
    "hero.subtitle": "Премиум говеда, овце и кози от доверени мрежи в цяла Европа.<br>Пълно регулаторно съответствие с ветеринарна сертификация и логистика.",
    "hero.cred1": "Сертифицирана от ЕС Търговия",
    "hero.cred2": "Одобрен Карантинен Център",
    "hero.cred3": "Глобална Логистика",
    "hero.cta1": "Запитване за Оферта",
    "hero.cta2": "Разгледай Услугите",
    "hero.scroll": "Превъртете надолу",
    "services.label": "Какво Правим",
    "services.title": "Нашите Основни Услуги",
    "services.desc": "Комплексни решения за животни от набавяне до доставка",
    "services.export.title": "Услуги за Износ на Животни",
    "services.export.desc": "Международен износ на животни с пълна ветеринарна и регулаторна съвместимост.",
    "services.trading.title": "Търговия с Животни",
    "services.trading.desc": "Професионално набавяне и търговия с говеда, овце и кози на пазарите в ЕС.",
    "services.quarantine.title": "Карантинни Съоръжения",
    "services.quarantine.desc": "Одобрени карантинни и задържащи съоръжения, подготвени за международен износ.",
    "services.link": "Научете повече",
    "process.label": "Процесът",
    "process.title": "Как Работи Нашият Процес на Износ",
    "process.desc": "От подбора до доставката, ние гарантираме качество на всяка стъпка",
    "process.step1.title": "Набавяне",
    "process.step1.desc": "Идентифицираме животни, отговарящи на вашите спецификации и изисквания за качество чрез нашата доверена мрежа от доставчици.",
    "process.step2.title": "Ветеринарни Прегледи",
    "process.step2.desc": "Животните преминават пълен здравен преглед и сертифициране според стандартите на ЕС и страната на дестинация.",
    "process.step3.title": "Карантина",
    "process.step3.desc": "Одобрени съоръжения осигуряват съответствие, мониторинг и готовност за износ.",
    "process.step4.title": "Износ и Логистика",
    "process.step4.desc": "Координация на транспорта, документация и доставка до крайната дестинация.",
    "updates.label": "Последни Новини",
    "updates.title": "Актуализации от Компанията",
    "updates.desc": "Скорошни операции, износ и пазарна активност",
    "updates.item1.date": "Февруари 2026",
    "updates.item1.title": "Износ на Говеда за Близкия Изток",
    "updates.item1.desc": "Успешно доставихме 500 глави премиум говеда на нашите партньори в ОАЕ.",
    "updates.item2.date": "Януари 2026",
    "updates.item2.title": "Разширяване на Съоръженията",
    "updates.item2.desc": "Разширихме карантинните съоръжения, за да отговорим на нарастващото търсене на износ.",
    "updates.item3.date": "Декември 2025",
    "updates.item3.title": "Ново Партньорство за Транспорт",
    "updates.item3.desc": "Партнирахме с водещи логистични доставчици за безпроблемен транспорт в целия ЕС.",
    "contact.label": "Свържете се",
    "contact.title": "Готови за Износ?<br>Да Поговорим.",
    "contact.desc": "Независимо дали ви трябват говеда, овце или кози, нашият екип е готов да се справи с вашите международни изисквания за животни с прецизност и грижа.",
    "contact.email": "Имейл",
    "contact.phone": "Телефон",
    "contact.location": "Местоположение",
    "contact.form.title": "Запитване за Оферта",
    "contact.form.firstName": "Име",
    "contact.form.lastName": "Фамилия",
    "contact.form.emailLabel": "Имейл Адрес",
    "contact.form.animal.placeholder": "Изберете Тип Животно",
    "contact.form.animal.cattle": "Говеда",
    "contact.form.animal.sheep": "Овце",
    "contact.form.animal.goats": "Кози",
    "contact.form.animal.mixed": "Смесено",
    "contact.form.animal.label": "Тип Животно",
    "contact.form.message": "Вашите Изисквания",
    "contact.form.submit": "Изпрати Запитване",
    "footer.desc": "Сертифицирани от ЕС услуги за търговия и износ на животни. Свързваме качествени животни с международните пазари от 2010 г.",
    "footer.links": "Бързи Връзки",
    "footer.services": "Услуги",
    "footer.logistics": "Логистика",
    "footer.contact": "Контакти",
    "footer.rights": "Всички права запазени.",
    "footer.privacy": "Политика за Поверителност",
    "footer.terms": "Общи Условия",
    //ABOUT
    "about.meta.title": "За Нас | Miran Livestock",
    "about.meta.description": "Научете повече за Miran Livestock - сертифицирана от ЕС компания за търговия и износ на животни, базирана в България.",
    "about.breadcrumb.home": "Начало",
    "about.hero.title": "За Miran Livestock",
    "about.hero.subtitle": "Свързваме качествени животни с международните пазари чрез доверени партньорства и сертифицирани операции.",
    "about.story.label": "Нашата История",
    "about.story.title": "Доверен Партньор в Животновъдството от 2010 г.",
    "about.story.lead": "Miran Livestock е сертифицирана от ЕС компания за търговия и износ на животни със седалище в Разград, България. Специализираме се в свързването на качествени говеда, овце и кози с международните пазари.",
    "about.story.p1": "Нашите операции обхващат цялата верига на износ на животни - от набавяне чрез нашата обширна мрежа от доверени европейски доставчици, до ветеринарна сертификация, управление на карантина и крайна доставка до дестинации в Близкия изток, Северна Африка и отвъд.",
    "about.story.p2": "С над 15 години опит изградихме репутация на надеждност, прозрачност и отличие в грижата за животните. Нашият екип от ветеринари, специалисти по логистика и търговски експерти работят заедно, за да гарантират, че всеки износ отговаря на най-високите стандарти.",
    "about.story.badge": "Години<br>Отличие",
    "about.stats.animals": "Изнесени Животни",
    "about.stats.countries": "Обслужвани Държави",
    "about.stats.satisfaction": "Удовлетворение на Клиенти",
    "about.mission.label": "Нашата Мисия",
    "about.mission.title": "Отличие във Всеки Износ",
    "about.mission.p1": "Вярваме, че качественият износ на животни изисква повече от просто логистика - изисква отдаденост към благосъстоянието на животните, стриктно спазване на международните разпоредби и истински партньорства с нашите клиенти.",
    "about.mission.p2": "Нашата мисия е да свържем пропастта между европейските производители на животни и международните пазари, гарантирайки, че всяко животно, което изнасяме, пристига здраво, документирано и готово за новата си среда.",
    "about.mission.point1": "Непреклонни стандарти за благосъстояние на животните",
    "about.mission.point2": "Пълно регулаторно съответствие и прозрачност",
    "about.mission.point3": "Дългосрочни партньорства с клиенти и доставчици",
    "about.values.label": "Нашите Принципи",
    "about.values.title": "Защо да Ни Изберете",
    "about.values.desc": "Ценностите, които движат всичко, което правим",
    "about.values.quality.title": "Сертифицирано Качество",
    "about.values.quality.desc": "Всяко животно отговаря на строгите стандарти на ЕС за здраве и благосъстояние преди износ. Пълна документация и проследяемост гарантирани.",
    "about.values.network.title": "Доверена Мрежа",
    "about.values.network.desc": "Дългогодишни отношения с проверени доставчици в цяла Европа и установени партньорства с купувачи по целия свят.",
    "about.values.efficiency.title": "Ефективна Логистика",
    "about.values.efficiency.desc": "Оптимизирана координация на транспорта, осигуряваща навременна, безопасна доставка. Ние се грижим за цялата документация и митнически изисквания.",
    "about.values.global.title": "Глобален Обхват",
    "about.values.global.desc": "Износ към пазари в Близкия изток, Северна Африка и отвъд. Разбираме разнообразните изисквания на пазарите.",
    "about.team.label": "Ръководство",
    "about.team.title": "Запознайте се с Екипа Ни",
    "about.team.desc": "Опитни професионалисти, посветени на вашия успех",
    "about.team.founder": "Основател и Изпълнителен Директор",
    "about.team.founder.desc": "15+ години в износа на животни, основава Miran Livestock през 2010 г.",
    "about.team.vet": "Главен Ветеринар",
    "about.team.vet.desc": "Специалист по ветеринарна медицина, сертифициран от ЕС, осигуряващ здравно съответствие.",
    "about.team.operations": "Оперативен Мениджър",
    "about.team.operations.desc": "Експерт по логистика и международни търговски разпоредби.",
    "about.team.sales": "Търговски Директор",
    "about.team.sales.desc": "Изграждане на трайни отношения с клиенти в над 25 държави.",
    "about.partners.label": "Доверени От",
    "about.partners.title": "Нашите Партньори",
    "about.partners.desc": "Сътрудничество с лидери в индустрията за постигане на отличие",
    "about.cta.title": "Да Работим Заедно",
    "about.cta.desc": "Партнирайте с доверено име в международния износ на животни.",
    "about.cta.button1": "Свържете се",
    "about.cta.button2": "Вижте Услугите",
    //CONTACT
    "contact.meta.title": "Контакти | Миран Животновъдство",
"contact.meta.description": "Свържете се с Миран Животновъдство за запитвания относно международен износ на животни. Офис в Разград, България.",
"contact.breadcrumb.home": "Начало",
"contact.hero.title": "Свържете се с нас",
"contact.hero.subtitle": "Готови за износ? Тук сме, за да помогнем. Свържете се за оферти, въпроси или запитвания за партньорство.",
"contact.card.address.title": "Посетете ни",
"contact.card.address.sub": "Главен офис и карантинни съоръжения",
"contact.card.phone.title": "Обадете ни се",
"contact.card.phone.sub": "Пон-Пет: 8:00 - 18:00 EET",
"contact.card.call": "Обадете се сега",
"contact.card.email.title": "Пишете ни",
"contact.card.email.sub": "Отговаряме до 24 часа",
"contact.card.send": "Изпратете имейл",
"contact.card.whatsapp.title": "WhatsApp",
"contact.card.whatsapp.sub": "Бързи отговори за спешни запитвания",
"contact.card.chat": "Започнете чат",
"contact.form.heading": "Изпратете ни съобщение",
"contact.form.intro": "Попълнете формата по-долу и ще се свържем с вас до 24 часа.",
"contact.form.firstName": "Име *",
"contact.form.lastName": "Фамилия *",
"contact.form.email": "Имейл адрес *",
"contact.form.phone": "Телефонен номер",
"contact.form.company": "Име на фирмата",
"contact.form.animal.cattle": "Говеда",
"contact.form.animal.sheep": "Овце",
"contact.form.animal.goats": "Кози",
"contact.form.animal.mixed": "Смесено",
"contact.form.animal.label": "Тип животно *",
"contact.form.quantity": "Приблизително количество (брой)",
"contact.form.destination.other": "Друга",
"contact.form.destination.label": "Държава на дестинация *",
"contact.form.message": "Вашето съобщение *",
"contact.form.submit": "Изпратете съобщение",
"contact.office.title": "Главен офис",
"contact.office.hours": "Работно време",
"contact.office.mon": "Понеделник - Петък:",
"contact.office.sat": "Събота:",
"contact.office.sun": "Неделя:",
"contact.office.closed": "Затворено",
"contact.faq.label": "ЧЗВ",
"contact.faq.title": "Често Задавани Въпроси",
"contact.faq.desc": "Бързи отговори на чести въпроси",
"contact.faq.q1": "Колко време отнема процесът на износ?",
"contact.faq.a1": "Типичният процес на износ отнема 2-4 седмици от потвърждаване на поръчката до доставката. Това включва набавяне, ветеринарни прегледи, карантина (7-14 дни в зависимост от дестинацията) и организиране на транспорта.",
"contact.faq.q2": "Какви документи предоставяте?",
"contact.faq.a2": "Предоставяме всички необходими документи за износ, включително: Ветеринарно здравно свидетелство, Сертификат за износ от ЕС, Сертификат за произход, Разрешителни CITES (ако се изисква) и митническа документация за държавата на дестинация.",
"contact.faq.q3": "До кои държави изнасяте?",
"contact.faq.a3": "Редовно изнасяме за ОАЕ, Катар, Саудитска Арабия, Кувейт, Йордания, Либия и други държави от Близкия изток и Северна Африка. Можем също така да организираме износ до други дестинации според вашите изисквания.",
"contact.faq.q4": "Какво е минималното количество за поръчка?",
"contact.faq.a4": "Приемаме поръчки с различни размери. Въпреки че сме специализирани в търговски обеми (50+ брой), можем да обсъдим по-малки поръчки в зависимост от дестинацията и наличността. Свържете се с нас за конкретни изисквания.",
"contact.faq.q5": "Как гарантирате благосъстоянието на животните по време на транспорт?",
"contact.faq.a5": "Благосъстоянието на животните е наш приоритет. Използваме одобрени от ЕС транспортни средства с подходяща вентилация, пространство и почивки. Всички пътувания са в съответствие с разпоредбите на ЕС за транспорт на животни и осигуряваме ветеринарен надзор за по-дълги маршрути.",
"contact.faq.q6": "Какви условия за плащане предлагате?",
"contact.faq.a6": "Обикновено изискваме 30% аванс при потвърждаване на поръчката, с останалите 70% дължими преди изпращане. За установени партньори можем да обсъдим алтернативни договорености за плащане, включително акредитиви.",
"contact.cta.title": "Готови да започнете вашия износ?",
"contact.cta.desc": "Екипът ни е на разположение, за да обсъдим вашите изисквания за животни.",
"contact.cta.call": "Обадете ни се сега",
"contact.cta.offers": "Вижте текущите оферти",
//SERVICES
"services.meta.title": "Услуги | Miran Livestock",
"services.meta.description": "Комплексни услуги за животни, включително износ, търговия и карантинни съоръжения.",
"services.hero.title": "Нашите Услуги",
"services.hero.subtitle": "Международно набавяне, търговия и износ на животни. Пълно съответствие с ветеринарни, карантинни и логистични операции.",
"services.breadcrumb.home": "Начало",
"services.export.tag": "Основна Услуга",
"services.export.title": "Услуги за Износ на Животни",
"services.export.lead": "Пълноценен международен износ на говеда, овце и кози, включително документация, ветеринарна сертификация и координация на транспорта.",
"services.export.feature1.title": "Процедури в Съответствие с ЕС",
"services.export.feature1.desc": "Целият износ отговаря на строгите разпоредби и стандарти на ЕС",
"services.export.feature2.title": "Ветеринарни Прегледи",
"services.export.feature2.desc": "Пълни здравни проверки и сертификати",
"services.export.feature3.title": "Митница и Документация",
"services.export.feature3.desc": "Пълно обработване на документи за гладко преминаване",
"services.export.feature4.title": "Координация на Транспорта",
"services.export.feature4.desc": "Цялостно управление на логистиката",
"services.export.cta": "Запитване за Износ",
"services.trading.tag": "Основна Услуга",
"services.trading.title": "Търговия с Животни",
"services.trading.lead": "Надеждно набавяне и търговия с качествени животни в цяла Европа и на международните пазари, съобразено с вашите специфични изисквания.",
"services.trading.feature1.title": "Доверена Мрежа от Доставчици",
"services.trading.feature1.desc": "Достъп до проверени ферми в целия ЕС",
"services.trading.feature2.title": "Подбор на Порода и Тегло",
"services.trading.feature2.desc": "Точно съответствие с вашите спецификации",
"services.trading.feature3.title": "Гъвкави Обеми",
"services.trading.feature3.desc": "От малки поръчки до големи търговски партиди",
"services.trading.feature4.title": "Пазарни Проучвания",
"services.trading.feature4.desc": "Експертни съвети за времето и ценообразуването",
"services.trading.cta": "Обсъждане на Търговски Опции",
"services.quarantine.tag": "Услуга за Съоръжения",
"services.quarantine.title": "Карантинни Съоръжения",
"services.quarantine.lead": "Одобрени карантинни и задържащи съоръжения, гарантиращи съответствие с разпоредбите на страната на дестинация и оптимално благосъстояние на животните.",
"services.quarantine.feature1.title": "Здравен Мониторинг",
"services.quarantine.feature1.desc": "Непрекъснат ветеринарен надзор",
"services.quarantine.feature2.title": "Протоколи за Изолация",
"services.quarantine.feature2.desc": "Строги биосигурностни мерки",
"services.quarantine.feature3.title": "Стандарти за Биосигурност",
"services.quarantine.feature3.desc": "Подобрени протоколи за хигиена и безопасност",
"services.quarantine.feature4.title": "Подготовка Преди Износ",
"services.quarantine.feature4.desc": "Проверки за готовност и документация",
"services.quarantine.cta": "Резервация на Място",
"services.process.label": "Процесът",
"services.process.title": "Как Работи",
"services.process.desc": "Четири стъпки от запитване до доставка",
"services.process.step1": "Набавяне",
"services.process.step1.desc": "Идентифицираме животни, отговарящи на вашите спецификации, чрез нашата доверена мрежа.",
"services.process.step2": "Ветеринарни Прегледи",
"services.process.step2.desc": "Пълен здравен преглед и сертифициране според стандартите на ЕС и дестинацията.",
"services.process.step3": "Карантина",
"services.process.step3.desc": "Мониторинг на съответствието и подготовка за готовност в одобрени съоръжения.",
"services.process.step4": "Износ и Логистика",
"services.process.step4.desc": "Координиран транспорт, документация и доставка до дестинация.",
"services.cta.title": "Готови да Започнете Вашия Износ?",
"services.cta.desc": "Екипът ни е на разположение, за да обсъдим вашите изисквания за животни и да предоставим персонализирана оферта.",
"services.cta.quote": "Запитване за Оферта",
"services.cta.call": "Обадете ни се Сега",
"offers.meta.title": "Оферти за Животни | Miran Livestock",
"offers.meta.description": "Разгледайте нашите налични говеда, овце и кози за износ. Всички животни са сертифицирани от ЕС и готови за износ.",
"offers.hero.title": "Текущи Оферти за Животни",
"offers.hero.subtitle": "Разгледайте нашите налични животни, готови за износ. Всички животни са сертифицирани от ЕС и готови за износ.",
"offers.breadcrumb.home": "Начало",
"offers.filter.all": "Всички Животни",
"offers.filter.cattle": "Говеда",
"offers.filter.sheep": "Овце",
"offers.filter.goats": "Кози",
"offers.card.available": "Налично Сега",
"offers.card.coming": "Очаква се Скоро",
"offers.card.head": "брой",
"offers.card.age": "Възраст",
"offers.card.weight": "Тегло",
"offers.card.health": "Здраве",
"offers.card.inquire": "Запитване Сега",
"offers.card.preorder": "Предварителна Поръчка",
"offers.cta.title": "Не Виждате Каквото Търсите?",
"offers.cta.desc": "Набавяме специфични породи и количества по заявка. Кажете ни вашите изисквания.",
"offers.cta.button": "Персонализирана Заявка"
  },
  
  tr: {
    "meta.title": "Miran Livestock | Uluslararası Hayvan Ticareti ve İhracat",
    "meta.description": "AB sertifikalı hayvan ticareti ve ihracat hizmetleri. Uluslararası pazarlar için sığır, koyun ve keçi.",
    "nav.home": "Ana Sayfa",
    "nav.services": "Hizmetler",
    "nav.offers": "Teklifler",
    "nav.about": "Hakkımızda",
    "nav.contact": "İletişim",
    "nav.language": "Dil:",
    "hero.badge": "AB Sertifikalı Operasyonlar",
    "hero.title": "Uluslararası Hayvan<br>Ticareti ve İhracat",
    "hero.subtitle": "Avrupa genelinde güvenilir ağlardan edinilen premium sığır, koyun ve keçi.<br>Veteriner sertifikasyon ve lojistik ile tam düzenleyici uyum.",
    "hero.cred1": "AB Sertifikalı Ticaret",
    "hero.cred2": "Onaylı Karantina",
    "hero.cred3": "Küresel Lojistik",
    "hero.cta1": "Teklif İste",
    "hero.cta2": "Hizmetleri Keşfet",
    "hero.scroll": "Keşfetmek için kaydır",
    "services.label": "Ne Yapıyoruz",
    "services.title": "Temel Hizmetlerimiz",
    "services.desc": "Kaynaklamadan teslimata kapsamlı hayvancılık çözümleri",
    "services.export.title": "Hayvan İhracat Hizmetleri",
    "services.export.desc": "Tam veteriner ve düzenleyici uyum ile uluslararası hayvan ihracat operasyonları.",
    "services.trading.title": "Hayvan Ticareti",
    "services.trading.desc": "AB pazarlarında sığır, koyun ve keçi profesyonel kaynaklama ve ticareti.",
    "services.quarantine.title": "Karantina Tesisleri",
    "services.quarantine.desc": "Uluslararası ihracata hazır onaylı karantina ve bekleme tesisleri.",
    "services.link": "Daha fazla bilgi",
    "process.label": "Süreç",
    "process.title": "İhracat Sürecimiz Nasıl İşler",
    "process.desc": "Seçimden teslimata, her adımda kaliteyi sağlıyoruz",
    "process.step1.title": "Kaynaklama",
    "process.step1.desc": "Güvenilir tedarikçi ağımız aracılığıyla spesifikasyonlarınıza ve kalite gereksinimlerinize uygun hayvanları belirliyoruz.",
    "process.step2.title": "Veteriner Kontrolleri",
    "process.step2.desc": "Hayvanlar, AB ve hedef ülke standartlarına göre tam sağlık muayenesi ve sertifikasyondan geçer.",
    "process.step3.title": "Karantina",
    "process.step3.desc": "Onaylı tesisler uyumluluk, izleme ve ihracat hazırlığı sağlar.",
    "process.step4.title": "İhracat ve Lojistik",
    "process.step4.desc": "Nihai varış noktasına ulaşım koordinasyonu, dokümantasyon ve teslimat.",
    "updates.label": "Son Haberler",
    "updates.title": "Şirket Güncellemeleri",
    "updates.desc": "Son operasyonlar, ihracatlar ve pazar aktivitesi",
    "updates.item1.date": "Şubat 2026",
    "updates.item1.title": "Ortadoğu'ya Sığır İhracatı",
    "updates.item1.desc": "BAE'deki ortaklarımıza 500 baş premium sığır başarıyla teslim edildi.",
    "updates.item2.date": "Ocak 2026",
    "updates.item2.title": "Tesis Genişletme",
    "updates.item2.desc": "Artan ihracat taleplerini karşılamak için karantina tesisleri genişletildi.",
    "updates.item3.date": "Aralık 2025",
    "updates.item3.title": "Yeni Ulaşım Ortaklığı",
    "updates.item3.desc": "Sorunsuz AB çapında ulaşım için önde gelen lojistik sağlayıcılarla ortaklık kuruldu.",
    "contact.label": "İletişime Geç",
    "contact.title": "İhracata Hazır mısınız?<br>Hadi Konuşalım.",
    "contact.desc": "Sığır, koyun veya keçiye ihtiyacınız olsun, ekibimiz uluslararası hayvancılık gereksinimlerinizi hassasiyet ve özenle karşılamaya hazır.",
    "contact.email": "E-posta",
    "contact.phone": "Telefon",
    "contact.location": "Konum",
    "contact.form.title": "Teklif İste",
    "contact.form.firstName": "Ad",
    "contact.form.lastName": "Soyad",
    "contact.form.emailLabel": "E-posta Adresi",
    "contact.form.animal.placeholder": "Hayvan Türü Seçin",
    "contact.form.animal.cattle": "Sığır",
    "contact.form.animal.sheep": "Koyun",
    "contact.form.animal.goats": "Keçi",
    "contact.form.animal.mixed": "Karışık",
    "contact.form.animal.label": "Hayvan Türü",
    "contact.form.message": "Gereksinimleriniz",
    "contact.form.submit": "Talep Gönder",
    "footer.desc": "AB sertifikalı hayvan ticareti ve ihracat hizmetleri. 2010'dan beri kaliteli hayvanları uluslararası pazarlarla buluşturuyoruz.",
    "footer.links": "Hızlı Bağlantılar",
    "footer.services": "Hizmetler",
    "footer.logistics": "Lojistik",
    "footer.contact": "İletişim",
    "footer.rights": "Tüm hakları saklıdır.",
    "footer.privacy": "Gizlilik Politikası",
    "footer.terms": "Kullanım Koşulları",
    //ABOUT
    "about.meta.title": "Hakkımızda | Miran Livestock",
    "about.meta.description": "Miran Livestock'ı keşfedin - Bulgaristan merkezli AB sertifikalı hayvan ticareti ve ihracat şirketi.",
    "about.breadcrumb.home": "Ana Sayfa",
    "about.hero.title": "Miran Livestock Hakkında",
    "about.hero.subtitle": "Güvenilir ortaklıklar ve sertifikalı operasyonlar aracılığıyla kaliteli hayvanları uluslararası pazarlarla buluşturuyoruz.",
    "about.story.label": "Hikayemiz",
    "about.story.title": "2010'dan Beri Güvenilir Hayvancılık Ortağı",
    "about.story.lead": "Miran Livestock, Bulgaristan'ın Razgrad şehrinde merkezi bulunan AB sertifikalı bir hayvan ticareti ve ihracat şirketidir. Sığır, koyun ve keçileri uluslararası pazarlarla buluşturmada uzmanız.",
    "about.story.p1": "Operasyonlarımız, güvenilir Avrupalı tedarikçilerimizin geniş ağı aracılığıyla kaynaklamadan, veteriner sertifikasyona, karantina yönetimine ve Ortadoğu, Kuzey Afrika ve ötesindeki destinasyonlara nihai teslimata kadar tüm hayvan ihracat zincirini kapsamaktadır.",
    "about.story.p2": "15 yılı aşkın deneyimimizle, güvenilirlik, şeffaflık ve hayvan refahında mükemmellik konusunda bir ün kazandık. Veterinerlerimiz, lojistik uzmanlarımız ve ticaret uzmanlarımızdan oluşan ekibimiz, her ihracatın en yüksek standartları karşılamasını sağlamak için birlikte çalışır.",
    "about.story.badge": "Yıllık<br>Mükemmellik",
    "about.stats.animals": "İhraç Edilen Hayvan",
    "about.stats.countries": "Hizmet Verilen Ülke",
    "about.stats.satisfaction": "Müşteri Memnuniyeti",
    "about.mission.label": "Misyonumuz",
    "about.mission.title": "Her İhracatta Mükemmellik",
    "about.mission.p1": "Kaliteli hayvan ihracatının sadece lojistikten daha fazlasını gerektirdiğine inanıyoruz—hayvan refahına adanmışlık, uluslararası düzenlemelere sıkı uyum ve müşterilerimizle samimi ortaklıklar gerektirir.",
    "about.mission.p2": "Misyonumuz, Avrupalı hayvan üreticileri ile uluslararası pazarlar arasındaki boşluğu köprülemek, ihraç ettiğimiz her hayvanın sağlıklı, belgelendirilmiş ve yeni ortamına hazır olarak varmasını sağlamaktır.",
    "about.mission.point1": "Hayvan refahında ödün vermeyen standartlar",
    "about.mission.point2": "Tam düzenleyici uyum ve şeffaflık",
    "about.mission.point3": "Müşteriler ve tedarikçilerle uzun vadeli ortaklıklar",
    "about.values.label": "İlkelerimiz",
    "about.values.title": "Neden Bizi Seçmelisiniz",
    "about.values.desc": "Yaptığımız her şeyi yönlendiren değerler",
    "about.values.quality.title": "Sertifikalı Kalite",
    "about.values.quality.desc": "Her hayvan, ihraç öncesinde sıkı AB sağlık ve refah standartlarını karşılar. Tam dokümantasyon ve izlenebilirlik garantilidir.",
    "about.values.network.title": "Güvenilir Ağ",
    "about.values.network.desc": "Avrupa genelinde doğrulanmış tedarikçilerle uzun süreli ilişkiler ve dünya çapında alıcılarla kurulmuş ortaklıklar.",
    "about.values.efficiency.title": "Verimli Lojistik",
    "about.values.efficiency.desc": "Zamanında, güvenli teslimatı sağlayan optimize edilmiş ulaşım koordinasyonu. Tüm dokümantasyon ve gümrük gereksinimlerini biz hallediyoruz.",
    "about.values.global.title": "Küresel Erişim",
    "about.values.global.desc": "Ortadoğu, Kuzey Afrika ve ötesindeki pazarlara ihracat. Çeşitli pazar gereksinimlerini anlıyoruz.",
    "about.team.label": "Liderlik",
    "about.team.title": "Ekibimizle Tanışın",
    "about.team.desc": "Başarınıza adanmış deneyimli profesyoneller",
    "about.team.founder": "Kurucu ve CEO",
    "about.team.founder.desc": "Hayvan ihracatında 15+ yıl, 2010'da Miran Livestock'ı kurdu.",
    "about.team.vet": "Baş Veteriner",
    "about.team.vet.desc": "Sağlık uygunluğunu sağlayan AB sertifikalı veteriner uzmanı.",
    "about.team.operations": "Operasyon Müdürü",
    "about.team.operations.desc": "Lojistik ve uluslararası ticaret düzenlemelerinde uzman.",
    "about.team.sales": "Satış Direktörü",
    "about.team.sales.desc": "25+ ülkede müşterilerle kalıcı ilişkiler kuruyor.",
    "about.partners.label": "Güvenenler",
    "about.partners.title": "Ortaklarımız",
    "about.partners.desc": "Mükemmellik sunmak için sektör liderleriyle işbirliği",
    "about.cta.title": "Birlikte Çalışalım",
    "about.cta.desc": "Uluslararası hayvan ihracatında güvenilir bir isimle ortaklık kurun.",
    "about.cta.button1": "İletişime Geç",
    "about.cta.button2": "Hizmetleri Gör",
    //CONTACT
    "contact.meta.title": "İletişim | Miran Livestock",
"contact.meta.description": "Uluslararası hayvan ihracatı sorgularınız için Miran Livestock ile iletişime geçin. Razgrad, Bulgaristan ofisi.",
"contact.breadcrumb.home": "Ana Sayfa",
"contact.hero.title": "İletişime Geçin",
"contact.hero.subtitle": "İhracata hazır mısınız? Yardım etmek için buradayız. Teklifler, sorular veya ortaklık sorguları için bize ulaşın.",
"contact.card.address.title": "Bizi Ziyaret Edin",
"contact.card.address.sub": "Ana ofis ve karantina tesisleri",
"contact.card.phone.title": "Bizi Arayın",
"contact.card.phone.sub": "Pzt-Cum: 8:00 - 18:00 DAS",
"contact.card.call": "Şimdi ara",
"contact.card.email.title": "Bize E-posta Gönderin",
"contact.card.email.sub": "24 saat içinde yanıt veriyoruz",
"contact.card.send": "E-posta gönder",
"contact.card.whatsapp.title": "WhatsApp",
"contact.card.whatsapp.sub": "Acil sorgular için hızlı yanıtlar",
"contact.card.chat": "Sohbet başlat",
"contact.form.heading": "Bize Mesaj Gönderin",
"contact.form.intro": "Aşağıdaki formu doldurun, 24 saat içinde size geri döneceğiz.",
"contact.form.firstName": "Ad *",
"contact.form.lastName": "Soyad *",
"contact.form.email": "E-posta Adresi *",
"contact.form.phone": "Telefon Numarası",
"contact.form.company": "Şirket Adı",
"contact.form.animal.cattle": "Sığır",
"contact.form.animal.sheep": "Koyun",
"contact.form.animal.goats": "Keçi",
"contact.form.animal.mixed": "Karışık",
"contact.form.animal.label": "Hayvan Türü *",
"contact.form.quantity": "Tahmini Miktar (baş)",
"contact.form.destination.other": "Diğer",
"contact.form.destination.label": "Hedef Ülke *",
"contact.form.message": "Mesajınız *",
"contact.form.submit": "Mesaj Gönder",
"contact.office.title": "Ana Ofis",
"contact.office.hours": "Çalışma Saatleri",
"contact.office.mon": "Pazartesi - Cuma:",
"contact.office.sat": "Cumartesi:",
"contact.office.sun": "Pazar:",
"contact.office.closed": "Kapalı",
"contact.faq.label": "SSS",
"contact.faq.title": "Sıkça Sorulan Sorular",
"contact.faq.desc": "Yaygın sorulara hızlı yanıtlar",
"contact.faq.q1": "İhracat süreci ne kadar sürer?",
"contact.faq.a1": "Tipik ihracat süreci, sipariş onayından teslimata kadar 2-4 hafta sürer. Buna kaynaklama, veteriner kontrolleri, karantina (hedefe bağlı olarak 7-14 gün) ve ulaşım düzenlemeleri dahildir.",
"contact.faq.q2": "Hangi belgeleri sağlıyorsunuz?",
"contact.faq.a2": "Veteriner Sağlık Sertifikası, AB İhracat Sertifikası, Menşe Sertifikası, CITES izinleri (gerekirse) ve hedef ülke için gümrük dokümantasyonu dahil olmak üzere tüm gerekli ihracat belgelerini sağlıyoruz.",
"contact.faq.q3": "Hangi ülkelere ihraç ediyorsunuz?",
"contact.faq.a3": "Düzenli olarak BAE, Katar, Suudi Arabistan, Kuveyt, Ürdün, Libya ve diğer Ortadoğu ve Kuzey Afrika ülkelerine ihracat yapıyoruz. İhtiyaçlarınıza bağlı olarak diğer destinasyonlara da ihracat düzenleyebiliriz.",
"contact.faq.q4": "Minimum sipariş miktarı nedir?",
"contact.faq.a4": "Çeşitli boyutlarda siparişleri karşılıyoruz. Ticari hacimlerde (50+ baş) uzmanlaşmış olsak da, destinasyona ve mevcut duruma bağlı olarak daha küçük siparişleri de görüşebiliriz. Özel gereksinimler için bizimle iletişime geçin.",
"contact.faq.q5": "Ulaşım sırasında hayvan refahını nasıl sağlıyorsunuz?",
"contact.faq.a5": "Hayvan refahı bizim en önemli önceliğimizdir. Uygun havalandırma, mesafe ve dinlenme duraklarına sahip AB onaylı taşıma araçları kullanıyoruz. Tüm yolculuklar AB hayvan taşıma yönetmeliklerine uygun olarak yapılır ve daha uzun rotalar için veteriner gözetimi sağlıyoruz.",
"contact.faq.q6": "Hangi ödeme koşullarını sunuyorsunuz?",
"contact.faq.a6": "Genellikle sipariş onayından sonra %30 peşinat, kalan %70'i sevkiyat öncesi talep ediyoruz. Kuruluş ortaklarımız için akreditif dahil alternatif ödeme düzenlemelerini görüşebiliriz.",
"contact.cta.title": "İhracatınıza Başlamaya Hazır mısınız?",
"contact.cta.desc": "Ekibimiz hayvancılık gereksinimlerinizi görüşmek için hazır bekliyor.",
"contact.cta.call": "Bizi Şimdi Arayın",
"contact.cta.offers": "Mevcut Teklifleri Görüntüle",
//SERVICES
"services.meta.title": "Hizmetler | Miran Livestock",
"services.meta.description": "İhracat, ticaret ve karantina tesisleri dahil kapsamlı hayvancılık hizmetleri.",
"services.hero.title": "Hizmetlerimiz",
"services.hero.subtitle": "Uluslararası hayvan temini, ticaret ve ihracat. Tam uyumlu veteriner, karantina ve lojistik operasyonları.",
"services.breadcrumb.home": "Ana Sayfa",
"services.export.tag": "Ana Hizmet",
"services.export.title": "Hayvan İhracat Hizmetleri",
"services.export.lead": "Sığır, koyun ve keçilerin uluslararası ihracatı için belgelendirme, veteriner sertifikasyonu ve ulaşım koordinasyonu dahil tam hizmet.",
"services.export.feature1.title": "AB Uyumlu Prosedürler",
"services.export.feature1.desc": "Tüm ihracatlar katı AB düzenlemelerine ve standartlarına uygun",
"services.export.feature2.title": "Veteriner Muayeneleri",
"services.export.feature2.desc": "Tam sağlık kontrolleri ve sertifikasyonlar",
"services.export.feature3.title": "Gümrük ve Belgelendirme",
"services.export.feature3.desc": "Sorunsuz gümrük geçişi için tam evrak işlemleri",
"services.export.feature4.title": "Ulaşım Koordinasyonu",
"services.export.feature4.desc": "Uçtan uca lojistik yönetimi",
"services.export.cta": "İhracat Hakkında Bilgi Al",
"services.trading.tag": "Temel Hizmet",
"services.trading.title": "Hayvan Ticareti",
"services.trading.lead": "Avrupa ve uluslararası pazarlarda özel gereksinimlerinize göre kaliteli hayvan temini ve ticareti.",
"services.trading.feature1.title": "Güvenilir Tedarikçi Ağı",
"services.trading.feature1.desc": "AB genelinde doğrulanmış çiftliklere erişim",
"services.trading.feature2.title": "Irk ve Ağırlık Seçimi",
"services.trading.feature2.desc": "Özelliklerinize tam uyum",
"services.trading.feature3.title": "Esnek Hacimler",
"services.trading.feature3.desc": "Küçük siparişlerden büyük ticari partilere",
"services.trading.feature4.title": "Piyasa Analizleri",
"services.trading.feature4.desc": "Zamanlama ve fiyatlandırma konusunda uzman rehberlik",
"services.trading.cta": "Ticaret Seçeneklerini Görüş",
"services.quarantine.tag": "Tesis Hizmeti",
"services.quarantine.title": "Karantina Tesisleri",
"services.quarantine.lead": "Hedef ülke düzenlemelerine uygunluk ve optimal hayvan refahı sağlayan onaylı karantina ve bekleme tesisleri.",
"services.quarantine.feature1.title": "Sağlık İzleme",
"services.quarantine.feature1.desc": "Sürekli veteriner gözetimi",
"services.quarantine.feature2.title": "İzolasyon Protokolleri",
"services.quarantine.feature2.desc": "Sıkı biyogüvenlik önlemleri",
"services.quarantine.feature3.title": "Biyogüvenlik Standartları",
"services.quarantine.feature3.desc": "Gelişmiş hijyen ve güvenlik protokolleri",
"services.quarantine.feature4.title": "İhraç Öncesi Hazırlık",
"services.quarantine.feature4.desc": "Hazır olma kontrolleri ve belgelendirme",
"services.quarantine.cta": "Tesis Alanı Rezervasyonu Yap",
"services.process.label": "Süreç",
"services.process.title": "Nasıl Çalışır",
"services.process.desc": "Sorgudan teslimata dört adım",
"services.process.step1": "Kaynaklama",
"services.process.step1.desc": "Güvenilir ağımız aracılığıyla özelliklerinize uygun hayvanları belirliyoruz.",
"services.process.step2": "Veteriner Kontrolleri",
"services.process.step2.desc": "AB ve hedef standartlarına göre tam sağlık muayenesi ve sertifikasyon.",
"services.process.step3": "Karantina",
"services.process.step3.desc": "Onaylı tesislerde uygunluk izleme ve hazırlık.",
"services.process.step4": "İhracat ve Lojistik",
"services.process.step4.desc": "Koordineli ulaşım, belgelendirme ve hedefe teslimat.",
"services.cta.title": "İhracatınıza Başlamaya Hazır mısınız?",
"services.cta.desc": "Ekibimiz hayvancılık gereksinimlerinizi görüşmek ve özelleştirilmiş bir teklif sunmak için hazır bekliyor.",
"services.cta.quote": "Teklif İste",
"services.cta.call": "Bizi Şimdi Arayın",

// OFFERS PAGE - Turkish
"offers.meta.title": "Hayvan Teklifleri | Miran Livestock",
"offers.meta.description": "İhracat için mevcut sığır, koyun ve keçilerimize göz atın. Tüm hayvanlar AB sertifikalı ve ihracata hazır.",
"offers.hero.title": "Mevcut Hayvan Teklifleri",
"offers.hero.subtitle": "İhracata hazır mevcut hayvanlarımıza göz atın. Tüm hayvanlar AB sertifikalı ve ihracata hazır.",
"offers.breadcrumb.home": "Ana Sayfa",
"offers.filter.all": "Tüm Hayvanlar",
"offers.filter.cattle": "Sığır",
"offers.filter.sheep": "Koyun",
"offers.filter.goats": "Keçi",
"offers.card.available": "Şimdi Mevcut",
"offers.card.coming": "Yakında Geliyor",
"offers.card.head": "baş",
"offers.card.age": "Yaş",
"offers.card.weight": "Ağırlık",
"offers.card.health": "Sağlık",
"offers.card.inquire": "Bilgi Al",
"offers.card.preorder": "Ön Sipariş",
"offers.cta.title": "Aradığınızı Bulamadınız mı?",
"offers.cta.desc": "Talep üzerine özel ırk ve miktarlarda temin ediyoruz. Gereksinimlerinizi bize bildirin.",
"offers.cta.button": "Özel Talep"

  },
  
  de: {
    "meta.title": "Miran Livestock | Internationaler Viehhandel & Export",
    "meta.description": "EU-zertifizierte Viehhandels- und Exportdienstleistungen. Rinder, Schafe & Ziegen für internationale Märkte.",
    "nav.home": "Startseite",
    "nav.services": "Dienstleistungen",
    "nav.offers": "Angebote",
    "nav.about": "Über Uns",
    "nav.contact": "Kontakt",
    "nav.language": "Sprache:",
    "hero.badge": "EU-Zertifizierte Betriebe",
    "hero.title": "Internationaler Viehhandel<br>& Export",
    "hero.subtitle": "Premium-Rinder, Schafe und Ziegen aus vertrauenswürdigen Netzwerken in ganz Europa.<br>Vollständige regulatorische Konformität mit veterinärer Zertifizierung und Logistik.",
    "hero.cred1": "EU-Zertifizierter Handel",
    "hero.cred2": "Genehmigte Quarantäne",
    "hero.cred3": "Globale Logistik",
    "hero.cta1": "Angebot Anfordern",
    "hero.cta2": "Dienstleistungen Entdecken",
    "hero.scroll": "Zum Entdecken scrollen",
    "services.label": "Was Wir Tun",
    "services.title": "Unsere Kernleistungen",
    "services.desc": "Umfassende Viehlösungen von der Beschaffung bis zur Lieferung",
    "services.export.title": "Viehexportdienstleistungen",
    "services.export.desc": "Internationale Viehexportoperationen mit vollständiger tierärztlicher und regulatorischer Konformität.",
    "services.trading.title": "Viehhandel",
    "services.trading.desc": "Professionelle Beschaffung und Vermarktung von Rindern, Schafen und Ziegen auf EU-Märkten.",
    "services.quarantine.title": "Quarantäneeinrichtungen",
    "services.quarantine.desc": "Genehmigte Quarantäne- und Halteeinrichtungen für den internationalen Export vorbereitet.",
    "services.link": "Mehr erfahren",
    "process.label": "Der Weg",
    "process.title": "Wie Unser Exportprozess Funktioniert",
    "process.desc": "Von der Auswahl bis zur Lieferung stellen wir bei jedem Schritt Qualität sicher",
    "process.step1.title": "Beschaffung",
    "process.step1.desc": "Wir identifizieren Vieh, das Ihren Spezifikationen und Qualitätsanforderungen durch unser vertrauenswürdiges Lieferantennetzwerk entspricht.",
    "process.step2.title": "Tierärztliche Kontrollen",
    "process.step2.desc": "Die Tiere unterziehen sich einer vollständigen Gesundheitsuntersuchung und Zertifizierung gemäß EU- und Bestimmungslandstandards.",
    "process.step3.title": "Quarantäne",
    "process.step3.desc": "Genehmigte Einrichtungen gewährleisten Konformität, Überwachung und Bereitschaft für den Export.",
    "process.step4.title": "Export & Logistik",
    "process.step4.desc": "Transportkoordination, Dokumentation und Lieferung zum Endziel.",
    "updates.label": "Neueste Nachrichten",
    "updates.title": "Unternehmensupdates",
    "updates.desc": "Kürzliche Operationen, Exporte und Marktaktivitäten",
    "updates.item1.date": "Februar 2026",
    "updates.item1.title": "Rinderexport in den Nahen Osten",
    "updates.item1.desc": "Erfolgreiche Lieferung von 500 Stück Premium-Rindern an unsere Partner in den VAE.",
    "updates.item2.date": "Januar 2026",
    "updates.item2.title": "Erweiterung der Einrichtungen",
    "updates.item2.desc": "Erweiterung der Quarantäneeinrichtungen, um die wachsenden Exportnachfragen zu decken.",
    "updates.item3.date": "Dezember 2025",
    "updates.item3.title": "Neue Transportpartnerschaft",
    "updates.item3.desc": "Partnerschaft mit führenden Logistikdienstleistern für nahtlosen EU-weiten Transport.",
    "contact.label": "Kontaktieren Sie Uns",
    "contact.title": "Bereit zum Exportieren?<br>Lassen Sie Uns Sprechen.",
    "contact.desc": "Ob Sie Rinder, Schafe oder Ziegen benötigen, unser Team ist bereit, Ihre internationalen Viehanforderungen mit Präzision und Sorgfalt zu erfüllen.",
    "contact.email": "E-Mail",
    "contact.phone": "Telefon",
    "contact.location": "Standort",
    "contact.form.title": "Angebot Anfordern",
    "contact.form.firstName": "Vorname",
    "contact.form.lastName": "Nachname",
    "contact.form.emailLabel": "E-Mail-Adresse",
    "contact.form.animal.placeholder": "Viehart Wählen",
    "contact.form.animal.cattle": "Rinder",
    "contact.form.animal.sheep": "Schafe",
    "contact.form.animal.goats": "Ziegen",
    "contact.form.animal.mixed": "Gemischt",
    "contact.form.animal.label": "Viehart",
    "contact.form.message": "Ihre Anforderungen",
    "contact.form.submit": "Anfrage Senden",
    "footer.desc": "EU-zertifizierte Viehhandels- und Exportdienstleistungen. Wir verbinden seit 2010 qualitativ hochwertiges Vieh mit internationalen Märkten.",
    "footer.links": "Schnelllinks",
    "footer.services": "Dienstleistungen",
    "footer.logistics": "Logistik",
    "footer.contact": "Kontakt",
    "footer.rights": "Alle Rechte vorbehalten.",
    "footer.privacy": "Datenschutzrichtlinie",
    "footer.terms": "Nutzungsbedingungen",
    //ABOUT
     "about.meta.title": "Über Uns | Miran Livestock",
    "about.meta.description": "Lernen Sie Miran Livestock kennen - EU-zertifizierte Viehhandels- und Exportgesellschaft mit Sitz in Bulgarien.",
    "about.breadcrumb.home": "Startseite",
    "about.hero.title": "Über Miran Livestock",
    "about.hero.subtitle": "Wir verbinden qualitativ hochwertiges Vieh mit internationalen Märkten durch vertrauenswürdige Partnerschaften und zertifizierte Operationen.",
    "about.story.label": "Unsere Geschichte",
    "about.story.title": "Vertrauenswürdiger Viehpartner seit 2010",
    "about.story.lead": "Miran Livestock ist eine EU-zertifizierte Viehhandels- und Exportgesellschaft mit Hauptsitz in Rasgrad, Bulgarien. Wir sind darauf spezialisiert, qualitativ hochwertige Rinder, Schafe und Ziegen mit internationalen Märkten zu verbinden.",
    "about.story.p1": "Unsere Operationen erstrecken sich über die gesamte Viehexportkette - von der Beschaffung durch unser umfangreiches Netzwerk vertrauenswürdiger europäischer Lieferanten über tierärztliche Zertifizierung und Quarantänemanagement bis zur endgültigen Lieferung an Ziele im Nahen Osten, Nordafrika und darüber hinaus.",
    "about.story.p2": "Mit über 15 Jahren Erfahrung haben wir uns einen Ruf für Zuverlässigkeit, Transparenz und Exzellenz im Tierschutz aufgebaut. Unser Team aus Tierärzten, Logistikspezialisten und Handelsexperten arbeitet zusammen, um sicherzustellen, dass jeder Export die höchsten Standards erfüllt.",
    "about.story.badge": "Jahre<br>Exzellenz",
    "about.stats.animals": "Exportierte Tiere",
    "about.stats.countries": "Bediente Länder",
    "about.stats.satisfaction": "Kundenzufriedenheit",
    "about.mission.label": "Unsere Mission",
    "about.mission.title": "Exzellenz in jedem Export",
    "about.mission.p1": "Wir glauben, dass qualitativ hochwertiger Viehexport mehr als nur Logistik erfordert - es erfordert Hingabe an den Tierschutz, strikte Einhaltung internationaler Vorschriften und echte Partnerschaften mit unseren Kunden.",
    "about.mission.p2": "Unsere Mission ist es, die Lücke zwischen europäischen Viehproduzenten und internationalen Märkten zu schließen und sicherzustellen, dass jedes Tier, das wir exportieren, gesund, dokumentiert und bereit für seine neue Umgebung ankommt.",
    "about.mission.point1": "Kompromisslose Tierschutzstandards",
    "about.mission.point2": "Vollständige regulatorische Konformität und Transparenz",
    "about.mission.point3": "Langfristige Partnerschaften mit Kunden und Lieferanten",
    "about.values.label": "Unsere Prinzipien",
    "about.values.title": "Warum Sie uns wählen sollten",
    "about.values.desc": "Die Werte, die alles, was wir tun, antreiben",
    "about.values.quality.title": "Zertifizierte Qualität",
    "about.values.quality.desc": "Jedes Tier erfüllt vor dem Export strikte EU-Gesundheits- und Tierschutzstandards. Vollständige Dokumentation und Rückverfolgbarkeit garantiert.",
    "about.values.network.title": "Vertrauenswürdiges Netzwerk",
    "about.values.network.desc": "Langjährige Beziehungen zu verifizierten Lieferanten in ganz Europa und etablierte Partnerschaften mit Käufern weltweit.",
    "about.values.efficiency.title": "Effiziente Logistik",
    "about.values.efficiency.desc": "Optimierte Transportkoordination für rechtzeitige, sichere Lieferung. Wir kümmern uns um alle Dokumentationen und Zollanforderungen.",
    "about.values.global.title": "Globale Reichweite",
    "about.values.global.desc": "Export in Märkte im Nahen Osten, Nordafrika und darüber hinaus. Wir verstehen vielfältige Marktanforderungen.",
    "about.team.label": "Führung",
    "about.team.title": "Lernen Sie unser Team kennen",
    "about.team.desc": "Erfahrene Fachleute, die Ihrem Erfolg gewidmet sind",
    "about.team.founder": "Gründer & CEO",
    "about.team.founder.desc": "15+ Jahre im Viehexport, gründete Miran Livestock 2010.",
    "about.team.vet": "Leitender Tierarzt",
    "about.team.vet.desc": "EU-zertifizierter Veterinärspezialist für Gesundheitskonformität.",
    "about.team.operations": "Betriebsleiter",
    "about.team.operations.desc": "Experte für Logistik und internationale Handelsvorschriften.",
    "about.team.sales": "Vertriebsleiter",
    "about.team.sales.desc": "Aufbau nachhaltiger Beziehungen zu Kunden in über 25 Ländern.",
    "about.partners.label": "Vertraut Von",
    "about.partners.title": "Unsere Partner",
    "about.partners.desc": "Zusammenarbeit mit Branchenführern zur Erreichung von Exzellenz",
    "about.cta.title": "Lassen Sie uns zusammenarbeiten",
    "about.cta.desc": "Partner mit einem vertrauenswürdigen Namen im internationalen Viehexport.",
    "about.cta.button1": "Kontakt aufnehmen",
    "about.cta.button2": "Dienstleistungen ansehen",
    //CONTACT
    "contact.meta.title": "Kontakt | Miran Livestock",
"contact.meta.description": "Nehmen Sie Kontakt mit Miran Livestock für internationale Viehexportanfragen auf. Büro in Razgrad, Bulgarien.",
"contact.breadcrumb.home": "Startseite",
"contact.hero.title": "Kontaktieren Sie uns",
"contact.hero.subtitle": "Bereit zum Exportieren? Wir sind hier, um zu helfen. Kontaktieren Sie uns für Angebote, Fragen oder Partnerschaftsanfragen.",
"contact.card.address.title": "Besuchen Sie uns",
"contact.card.address.sub": "Hauptbüro und Quarantäneeinrichtungen",
"contact.card.phone.title": "Rufen Sie uns an",
"contact.card.phone.sub": "Mo-Fr: 8:00 - 18:00 EET",
"contact.card.call": "Jetzt anrufen",
"contact.card.email.title": "Schreiben Sie uns",
"contact.card.email.sub": "Wir antworten innerhalb von 24 Stunden",
"contact.card.send": "E-Mail senden",
"contact.card.whatsapp.title": "WhatsApp",
"contact.card.whatsapp.sub": "Schnelle Antworten für dringende Anfragen",
"contact.card.chat": "Chat starten",
"contact.form.heading": "Senden Sie uns eine Nachricht",
"contact.form.intro": "Füllen Sie das Formular unten aus und wir melden uns innerhalb von 24 Stunden bei Ihnen.",
"contact.form.firstName": "Vorname *",
"contact.form.lastName": "Nachname *",
"contact.form.email": "E-Mail-Adresse *",
"contact.form.phone": "Telefonnummer",
"contact.form.company": "Firmenname",
"contact.form.animal.cattle": "Rinder",
"contact.form.animal.sheep": "Schafe",
"contact.form.animal.goats": "Ziegen",
"contact.form.animal.mixed": "Gemischt",
"contact.form.animal.label": "Viehart *",
"contact.form.quantity": "Geschätzte Menge (Stück)",
"contact.form.destination.other": "Andere",
"contact.form.destination.label": "Zielland *",
"contact.form.message": "Ihre Nachricht *",
"contact.form.submit": "Nachricht senden",
"contact.office.title": "Hauptbüro",
"contact.office.hours": "Geschäftszeiten",
"contact.office.mon": "Montag - Freitag:",
"contact.office.sat": "Samstag:",
"contact.office.sun": "Sonntag:",
"contact.office.closed": "Geschlossen",
"contact.faq.label": "FAQ",
"contact.faq.title": "Häufig gestellte Fragen",
"contact.faq.desc": "Schnelle Antworten auf häufige Fragen",
"contact.faq.q1": "Wie lange dauert der Exportprozess?",
"contact.faq.a1": "Der typische Exportprozess dauert 2-4 Wochen von der Auftragsbestätigung bis zur Lieferung. Dazu gehören Beschaffung, tierärztliche Kontrollen, Quarantäne (7-14 Tage je nach Ziel) und Transportarrangements.",
"contact.faq.q2": "Welche Unterlagen stellen Sie zur Verfügung?",
"contact.faq.a2": "Wir stellen alle erforderlichen Exportunterlagen zur Verfügung, einschließlich: Tierärztliches Gesundheitszeugnis, EU-Exportzertifikat, Ursprungszertifikat, CITES-Genehmigungen (falls erforderlich) und Zollunterlagen für das Zielland.",
"contact.faq.q3": "In welche Länder exportieren Sie?",
"contact.faq.a3": "Wir exportieren regelmäßig in die VAE, Katar, Saudi-Arabien, Kuwait, Jordanien, Libyen und andere Länder des Nahen Ostens und Nordafrikas. Wir können auch Exporte in andere Ziele je nach Ihren Anforderungen arrangieren.",
"contact.faq.q4": "Was ist die Mindestbestellmenge?",
"contact.faq.a4": "Wir bearbeiten Bestellungen in verschiedenen Größen. Während wir auf Handelsvolumen (50+ Stück) spezialisiert sind, können wir je nach Ziel und Verfügbarkeit auch kleinere Bestellungen besprechen. Kontaktieren Sie uns für spezifische Anforderungen.",
"contact.faq.q5": "Wie stellen Sie den Tierschutz während des Transports sicher?",
"contact.faq.a5": "Tierschutz hat für uns oberste Priorität. Wir verwenden EU-zugelassene Transportfahrzeuge mit angemessener Belüftung, Platz und Raststätten. Alle Fahrten entsprechen den EU-Vorschriften für den Tiertransport, und wir stellen tierärztliche Aufsicht für längere Strecken bereit.",
"contact.faq.q6": "Welche Zahlungsbedingungen bieten Sie an?",
"contact.faq.a6": "Wir verlangen in der Regel eine 30%ige Anzahlung bei Auftragsbestätigung, mit den restlichen 70% vor dem Versand. Für etablierte Partner können wir alternative Zahlungsvereinbarungen einschließlich Akkreditive besprechen.",
"contact.cta.title": "Bereit, Ihren Export zu starten?",
"contact.cta.desc": "Unser Team steht bereit, um Ihre Viehanforderungen zu besprechen.",
"contact.cta.call": "Rufen Sie uns jetzt an",
"contact.cta.offers": "Aktuelle Angebote ansehen",
//SERVICES
"services.meta.title": "Dienstleistungen | Miran Livestock",
"services.meta.description": "Umfassende Viehhaltungsdienstleistungen inklusive Export, Handel und Quarantäneeinrichtungen.",
"services.hero.title": "Unsere Dienstleistungen",
"services.hero.subtitle": "Internationale Viehbeschaffung, Handel und Export. Vollständig konforme veterinärmedizinische, Quarantäne- und Logistikoperationen.",
"services.breadcrumb.home": "Startseite",
"services.export.tag": "Hauptdienst",
"services.export.title": "Viehexportdienstleistungen",
"services.export.lead": "Vollständiger internationaler Export von Rindern, Schafen und Ziegen, einschließlich Dokumentation, veterinärer Zertifizierung und Transportkoordination.",
"services.export.feature1.title": "EU-konforme Verfahren",
"services.export.feature1.desc": "Alle Exporte entsprechen strengen EU-Vorschriften und -Standards",
"services.export.feature2.title": "Tierärztliche Untersuchungen",
"services.export.feature2.desc": "Vollständige Gesundheitskontrollen und Zertifizierungen",
"services.export.feature3.title": "Zoll und Dokumentation",
"services.export.feature3.desc": "Vollständige Abwicklung der Papierarbeit für reibungslose Zollabfertigung",
"services.export.feature4.title": "Transportkoordination",
"services.export.feature4.desc": "Umfassendes Logistikmanagement",
"services.export.cta": "Export anfragen",
"services.trading.tag": "Kernservice",
"services.trading.title": "Viehhandel",
"services.trading.lead": "Zuverlässige Beschaffung und Vermarktung von Qualitätsvieh in ganz Europa und auf internationalen Märkten, maßgeschneidert auf Ihre spezifischen Anforderungen.",
"services.trading.feature1.title": "Vertrauenswürdiges Lieferantennetzwerk",
"services.trading.feature1.desc": "Zugang zu überprüften Farmen in der gesamten EU",
"services.trading.feature2.title": "Rassen- und Gewichtsauswahl",
"services.trading.feature2.desc": "Präzise Abstimmung auf Ihre Spezifikationen",
"services.trading.feature3.title": "Flexible Volumina",
"services.trading.feature3.desc": "Von kleinen Bestellungen bis zu großen kommerziellen Chargen",
"services.trading.feature4.title": "Markteinblicke",
"services.trading.feature4.desc": "Fachkundige Beratung zu Zeitpunkt und Preisgestaltung",
"services.trading.cta": "Handelsoptionen besprechen",
"services.quarantine.tag": "Einrichtungsservice",
"services.quarantine.title": "Quarantäneeinrichtungen",
"services.quarantine.lead": "Genehmigte Quarantäne- und Halteeinrichtungen, die die Einhaltung der Bestimmungslandvorschriften und optimale Tierwohlbedingungen gewährleisten.",
"services.quarantine.feature1.title": "Gesundheitsüberwachung",
"services.quarantine.feature1.desc": "Kontinuierliche tierärztliche Aufsicht",
"services.quarantine.feature2.title": "Isolationsprotokolle",
"services.quarantine.feature2.desc": "Strenge biosecurity-Maßnahmen",
"services.quarantine.feature3.title": "Biosecurity-Standards",
"services.quarantine.feature3.desc": "Erhöhte Hygiene- und Sicherheitsprotokolle",
"services.quarantine.feature4.title": "Vor-Export-Vorbereitung",
"services.quarantine.feature4.desc": "Bereitschaftskontrollen und Dokumentation",
"services.quarantine.cta": "Platz reservieren",
"services.process.label": "Der Prozess",
"services.process.title": "Wie es funktioniert",
"services.process.desc": "Vier Schritte von der Anfrage bis zur Lieferung",
"services.process.step1": "Beschaffung",
"services.process.step1.desc": "Wir identifizieren Vieh, das Ihren Spezifikationen durch unser vertrauenswürdiges Netzwerk entspricht.",
"services.process.step2": "Tierärztliche Kontrollen",
"services.process.step2.desc": "Vollständige Gesundheitsuntersuchung und Zertifizierung gemäß EU- und Bestimmungsstandards.",
"services.process.step3": "Quarantäne",
"services.process.step3.desc": "Konformitätsüberwachung und Bereitschaftsvorbereitung in genehmigten Einrichtungen.",
"services.process.step4": "Export und Logistik",
"services.process.step4.desc": "Koordinierter Transport, Dokumentation und Lieferung zum Zielort.",
"services.cta.title": "Bereit, Ihren Export zu starten?",
"services.cta.desc": "Unser Team steht bereit, um Ihre Viehanforderungen zu besprechen und ein maßgeschneidertes Angebot zu unterbreiten.",
"services.cta.quote": "Angebot anfordern",
"services.cta.call": "Rufen Sie uns jetzt an",

// OFFERS PAGE - German
"offers.meta.title": "Viehangebote | Miran Livestock",
"offers.meta.description": "Durchsuchen Sie unsere verfügbaren Rinder, Schafe und Ziegen für den Export. Alles Vieh ist EU-zertifiziert und exportbereit.",
"offers.hero.title": "Aktuelle Viehangebote",
"offers.hero.subtitle": "Durchsuchen Sie unsere verfügbaren Tiere, die für den Export bereit sind. Alles Vieh ist EU-zertifiziert und exportbereit.",
"offers.breadcrumb.home": "Startseite",
"offers.filter.all": "Alle Tiere",
"offers.filter.cattle": "Rinder",
"offers.filter.sheep": "Schafe",
"offers.filter.goats": "Ziegen",
"offers.card.available": "Jetzt verfügbar",
"offers.card.coming": "Demnächst verfügbar",
"offers.card.head": "Stück",
"offers.card.age": "Alter",
"offers.card.weight": "Gewicht",
"offers.card.health": "Gesundheit",
"offers.card.inquire": "Anfragen",
"offers.card.preorder": "Vorbestellen",
"offers.cta.title": "Nicht das Richtige gefunden?",
"offers.cta.desc": "Wir beschaffen auf Anfrage spezifische Rassen und Mengen. Teilen Sie uns Ihre Anforderungen mit.",
"offers.cta.button": "Individuelle Anfrage"
  }
};

// Translation function
function translatePage(lang) {
  console.log('Translating to:', lang);
  
  const texts = translations[lang];
  if (!texts) {
    console.error('No translations for:', lang);
    return;
  }
  
  // Update all elements with data-i18n
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (texts[key]) {
      el.innerHTML = texts[key];
    }
  });
  
  // Update active button states
  document.querySelectorAll('.lang-btn').forEach(btn => {
    if (btn.dataset.lang === lang) {
      btn.classList.add('active');
    } else {
      btn.classList.remove('active');
    }
  });
  
  // Save preference
  localStorage.setItem('language', lang);
  document.documentElement.lang = lang;
}

// Initialize when DOM is ready
document.addEventListener('DOMContentLoaded', function() {
  console.log('Language system loaded');
  
  // Get saved language or default to English
  const savedLang = localStorage.getItem('language') || 'en';
  translatePage(savedLang);
  
  // Bind click events to all language buttons
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.addEventListener('click', function(e) {
      e.preventDefault();
      e.stopPropagation();
      const lang = this.dataset.lang;
      console.log('Clicked:', lang);
      translatePage(lang);
    });
  });
});